### ISSUE TITLE
作为一个老人，对于欢迎新人来说，最大的感受

### ISSUE THREAD

**Issue by ghost** [AlexanderMisel/Wikipedia#1]
1. 说明文字太长
2. 警告太含糊
3. 操作方法不明确

然后有些新手就吓跑了。

举一个具体例子，假如有新手加入[[:en:xxx]]，我们的警告不应该是{{uw-mos1}}，而应该是“您好，请不要加入类似[[:en:xxx]]这样的链接。如果中文维基有对应条目，不管质量如何，请链接至中文条目。如果中文没有对应条目，它应该叫做“条目”，而对应英文维基的条目名叫做article，请使用{{tsl|en|article|条目}}。谢谢您的合作。”

再举个例子，[[MediaWiki talk:Abusefilter-warning-moshead]]

**Comment by brynne8** [comment]
欢迎帮助修订这本书。无论是否用TeX。
